apiVersion: v1
kind: Secret
metadata:
  name: cmp-git-ssh-key
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: manifest-validator-cmp
    app.kubernetes.io/component: credentials
type: kubernetes.io/ssh-auth
stringData:
  # Replace with your actual SSH private key
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----

  # GitHub known hosts
  known_hosts: |
